// Parsers/serializers for the workspace Turtle shapes (MODEL.md). The hub
// reads/writes the same documents the seed/compiler scripts emit — parsing is
// shape-tolerant regex over those known emissions (v1; a real RDF lib can
// replace this without changing callers).

export type Role = "Owner" | "Member" | "Guest";

export type Membership = {
  agent: string; // WebID
  role: Role;
  kind: "Worker" | null;
  name: string | null;
  org: string | null;
};

export type ProjectMeta = {
  id: string;
  title: string;
  description: string | null;
  status: string;
  startDate: string;
  endDate: string;
  members: Membership[];
};

const unesc = (s: string) => s.replace(/\\"/g, '"').replace(/\\n/g, "\n").replace(/\\\\/g, "\\");

/**
 * Split a document into subject blocks. NOT on blank lines — the workspace's
 * `wf:description """…"""` literals are multi-paragraph markdown, so blank
 * lines occur INSIDE blocks; splitting there silently drops descriptions.
 */
const splitBlocks = (ttl: string) => ttl.split(/\n(?=<#)/);

export function parseProject(ttl: string): ProjectMeta {
  const members: Membership[] = [];
  for (const b of splitBlocks(ttl)) {
    if (!/a ws:Membership\b/.test(b)) continue;
    const agent = b.match(/ws:agent\s+<([^>]+)>/)?.[1];
    const role = b.match(/ws:role\s+ws:(\w+)/)?.[1] as Role | undefined;
    if (!agent || !role) continue;
    members.push({
      agent,
      role,
      kind: /ws:agentKind\s+ws:Worker/.test(b) ? "Worker" : null,
      name: b.match(/ws:name\s+"((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
      org: b.match(/ws:org\s+"((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
    });
  }
  return {
    id: ttl.match(/dct:identifier "((?:[^"\\]|\\.)*)"/)?.[1] ?? "",
    title: unesc(ttl.match(/dct:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? ""),
    description: ttl.match(/dct:description "((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
    status: ttl.match(/ws:status "([^"]+)"/)?.[1] ?? "active",
    startDate: ttl.match(/ws:startDate "([\d-]+)"/)?.[1] ?? "",
    endDate: ttl.match(/ws:endDate "([\d-]+)"/)?.[1] ?? "",
    members,
  };
}

// ------------------------------------------------------------------- company
// The owners-only workspace surface (MODEL.md → Company surface), read by the
// Workspace hub. Same shape-tolerant regex parsing as the rest of this module.

export type Company = {
  title: string;
  legalName: string;
  description: string | null;
  url: string | null;
  owners: string[]; // WebIDs
};

export function parseCompany(ttl: string): Company {
  return {
    title: unesc(ttl.match(/dct:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? ""),
    legalName: unesc(ttl.match(/schema:legalName "((?:[^"\\]|\\.)*)"/)?.[1] ?? ""),
    description: unesc(ttl.match(/dct:description "((?:[^"\\]|\\.)*)"/)?.[1] ?? "") || null,
    url: ttl.match(/schema:url "((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
    owners: [...ttl.matchAll(/ws:owner\s+<([^>]+)>/g)].map((m) => m[1]),
  };
}

export type OrgKind = "self" | "partner" | "research" | "customer";

export type OrgInfo = {
  id: string;
  title: string;
  kind: OrgKind;
  aliases: string[];
};

/** Parse the partner-org registry (company/orgs.ttl). */
export function parseOrgRegistry(ttl: string): OrgInfo[] {
  const orgs: OrgInfo[] = [];
  for (const b of splitBlocks(ttl)) {
    const id = b.match(/^<#([\w-]+)>/m)?.[1];
    if (!id || !/a schema:Organization\b/.test(b)) continue;
    orgs.push({
      id,
      title: unesc(b.match(/dct:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? id),
      kind: (b.match(/ws:orgKind "([^"]+)"/)?.[1] as OrgKind) ?? "partner",
      aliases: [...b.matchAll(/ws:alias "((?:[^"\\]|\\.)*)"/g)].map((m) => unesc(m[1])),
    });
  }
  return orgs;
}

// ------------------------------------------------------------------- tracker
// The tracker is a `.mind`-native split projection generated by the sync service
// (docs/PRD-git-issues.md): tracker.ttl (vocab), epics.ttl (epics), state.ttl
// (folded issues). state.ttl issue blocks use colon-prefixed rdf:type classes
// (`a :Todo , :General`), ULID-or-TASK-NNN subjects, `mc:epic <epics.ttl#slug>`,
// and EmAI-local `ekai:due`/`ekai:gitPath`. The bootstrap preserves TASK-NNN ids
// and AP-slug epics, so existing permalinks keep resolving; new issues get ULIDs
// (shown via the derived `handle`). state is read back from rdf:type and snapped
// to the hub's fixed IssueState union.

export const STATES = ["backlog", "todo", "in-progress", "review", "done", "cancelled"] as const;
export type IssueState = (typeof STATES)[number];

/** Hub IssueState → the Turtle rdf:type class local-name (className(stateId)). */
export const STATE_CLASS: Record<IssueState, string> = {
  backlog: "Backlog",
  todo: "Todo",
  "in-progress": "InProgress",
  review: "Review",
  done: "Done",
  cancelled: "Cancelled",
};
// Turtle class local-name → hub IssueState. Tolerant of `.mind` configs that name
// the in-progress state `doing` (className → "Doing") and US spelling.
const CLASS_STATE: Record<string, IssueState> = {
  Backlog: "backlog",
  Todo: "todo",
  InProgress: "in-progress",
  Doing: "in-progress",
  Review: "review",
  Done: "done",
  Cancelled: "cancelled",
  Canceled: "cancelled",
};

/** "in-progress" → "InProgress" (a Turtle class local-name). */
const className = (id: string) =>
  id.split(/[^A-Za-z0-9]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("");

/** Short display handle: keep `TASK-019`-style ids verbatim; derive `MC-NNNN`
    for ULID ids (which are unreadable on a board card). */
const handleOf = (id: string, number: number) =>
  /^[A-Za-z]+-\d+$/.test(id) ? id : number ? `MC-${String(number).padStart(4, "0")}` : id;

export type Epic = {
  id: string; // AP-slug
  number: number;
  title: string;
  status: string;
  lead: string | null;
  description: string;
};

export type Issue = {
  id: string; // canonical: TASK-NNN (bootstrapped) or ULID (created in-app)
  handle: string; // display label (id, or MC-NNNN for ULIDs)
  number: number;
  title: string;
  state: IssueState;
  epic: string | null; // AP-slug
  category: string | null; // rdf:type category class (e.g. "General")
  priority: string | null;
  created: string | null;
  modified: string | null;
  due: string | null;
  assignee: string | null; // WebID
  ownerName: string | null;
  gitPath: string | null; // repo-relative issue folder (under .mind/issues/); for commit-back
  description: string;
};

export type Tracker = { title: string; epics: Epic[]; issues: Issue[] };

function parseIssueBlock(b: string): Issue | null {
  const id = b.match(/^<#([\w-]+)>/m)?.[1];
  if (!id || !/wf:tracker\s+:this/.test(b)) return null; // only issue subjects
  // `a :Todo , :General ;` — isolate the rdf:type list, split state vs category.
  // Anchor the `a` predicate to the start of its own line: a bare `\ba` would
  // also match the "a" inside a title like "Invite a collaborator", stealing the
  // type list (and silently defaulting every such issue to `todo`).
  const aList = b.match(/^\s*a\s+([^;.\n]+)/m)?.[1] ?? "";
  const classes = [...aList.matchAll(/:([A-Za-z][A-Za-z0-9]*)/g)].map((m) => m[1]);
  const stateClass = classes.find((c) => c in CLASS_STATE) ?? "Todo";
  const number = parseInt(b.match(/mc:number\s+(\d+)/)?.[1] ?? "0", 10);
  return {
    id,
    handle: handleOf(id, number),
    number,
    title: unesc(b.match(/dc:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? id),
    state: CLASS_STATE[stateClass] ?? "todo",
    epic: b.match(/mc:epic\s+<(?:epics\.ttl)?#([\w-]+)>/)?.[1] ?? null,
    category: classes.find((c) => !(c in CLASS_STATE)) ?? null,
    priority: b.match(/mc:priority "([^"]+)"/)?.[1] ?? null,
    created: b.match(/dct:created "([\d-]+)"/)?.[1] ?? null,
    modified: b.match(/dct:modified "([\d-]+)"/)?.[1] ?? null,
    due: b.match(/(?:ekai|mindp):due "([\d-]+)"/)?.[1] ?? null,
    assignee: b.match(/wf:assignee <([^>]+)>/)?.[1] ?? null,
    ownerName: b.match(/(?:ekai|mindp):ownerName "((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
    gitPath: b.match(/(?:ekai|mindp):gitPath "((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
    description: b.match(/wf:description """([\s\S]*?)"""/)?.[1]?.trim() ?? "",
  };
}

/** Parse the folded issues out of state.ttl. */
export function parseState(stateTtl: string): Issue[] {
  const issues: Issue[] = [];
  for (const b of splitBlocks(stateTtl)) {
    const issue = parseIssueBlock(b);
    if (issue) issues.push(issue);
  }
  issues.sort((a, b) => a.number - b.number);
  return issues;
}

/** Parse the epics out of epics.ttl. */
export function parseEpics(epicsTtl: string): Epic[] {
  const epics: Epic[] = [];
  for (const b of splitBlocks(epicsTtl)) {
    const id = b.match(/^<#([\w-]+)>/m)?.[1];
    if (!id || !/a mc:Epic/.test(b)) continue;
    epics.push({
      id,
      number: parseInt(b.match(/mc:number\s+(\d+)/)?.[1] ?? "0", 10),
      title: unesc(b.match(/dct:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? id),
      status: b.match(/mc:status "([^"]+)"/)?.[1] ?? "planned",
      lead: b.match(/(?:ekai|mindp):lead "((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
      description: b.match(/dct:description """([\s\S]*?)"""/)?.[1]?.trim() ?? "",
    });
  }
  epics.sort((a, b) => a.number - b.number);
  return epics;
}

/** Join the three native docs into a Tracker. */
export function parseTracker(docs: { vocab: string; state: string; epics: string }): Tracker {
  return {
    title: unesc(docs.vocab.match(/dct:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? ""),
    epics: parseEpics(docs.epics),
    issues: parseState(docs.state),
  };
}

/** Serialize an issue into a native state.ttl block (the shape the build emits).
    Preserves mc:number, category, and ekai:gitPath so an optimistic in-place
    rewrite round-trips until the next forward sync regenerates the doc. */
function serializeIssue(i: Issue): string {
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const lines = [`<#${i.id}>`, `    wf:tracker :this ;`, `    mc:number ${i.number} ;`];
  if (i.epic) lines.push(`    mc:epic <epics.ttl#${i.epic}> ;`);
  lines.push(`    dc:title "${esc(i.title)}" ;`);
  lines.push(`    a :${STATE_CLASS[i.state]} , :${i.category ? className(i.category) : "General"} ;`);
  if (i.created) lines.push(`    dct:created "${i.created}"^^xsd:date ;`);
  if (i.modified) lines.push(`    dct:modified "${i.modified}"^^xsd:date ;`);
  if (i.due) lines.push(`    mindp:due "${i.due}"^^xsd:date ;`);
  if (i.priority) lines.push(`    mc:priority "${esc(i.priority)}" ;`);
  if (i.assignee) lines.push(`    wf:assignee <${i.assignee}> ;`);
  if (i.gitPath) lines.push(`    mindp:gitPath "${esc(i.gitPath)}" ;`);
  const desc = i.description.replace(/"""/g, '\\"\\"\\"');
  lines.push(`    wf:description """${desc}""" .`);
  return lines.join("\n");
}

export type IssuePatch = Partial<
  Pick<Issue, "title" | "state" | "epic" | "priority" | "due" | "assignee" | "description">
>;

/** Rewrite one issue's fields in state.ttl (parse block → patch → re-serialize). */
export function rewriteIssue(stateTtl: string, issueId: string, patch: IssuePatch): string {
  const blocks = splitBlocks(stateTtl);
  const idx = blocks.findIndex((b) => b.startsWith(`<#${issueId}>`));
  if (idx === -1) throw new Error(`issue ${issueId} not found`);
  const tail = blocks[idx].match(/\.\s*$/)?.[0].slice(1) ?? "";
  const current = parseIssueBlock(blocks[idx]);
  if (!current) throw new Error(`issue ${issueId} not parseable`);
  const updated: Issue = { ...current, ...patch, modified: new Date().toISOString().slice(0, 10) };
  blocks[idx] = serializeIssue(updated) + tail;
  return blocks.join("\n");
}

/** Move an issue to a new state (optimistic in-place state.ttl rewrite; the
    forward sync from git is authoritative and self-heals on the next run). */
export function rewriteIssueState(stateTtl: string, issueId: string, state: IssueState): string {
  return rewriteIssue(stateTtl, issueId, { state });
}

/** Append a new issue block to state.ttl. `id` is supplied by the caller (the
    commit-back route mints a ULID); `number` is provisional until the next sync
    assigns the canonical mc:number from the git fold. */
export function appendIssue(
  stateTtl: string,
  input: {
    id: string;
    title: string;
    state: IssueState;
    epic: string | null;
    due: string | null;
    assignee: string | null;
    gitPath?: string | null;
    description?: string;
  },
): { ttl: string; id: string } {
  const numbers = [...stateTtl.matchAll(/mc:number\s+(\d+)/g)].map((m) => parseInt(m[1], 10));
  const next = Math.max(0, ...numbers) + 1;
  const today = new Date().toISOString().slice(0, 10);
  const block = serializeIssue({
    id: input.id,
    handle: handleOf(input.id, next),
    number: next,
    title: input.title,
    state: input.state,
    epic: input.epic,
    category: "General",
    priority: null,
    created: today,
    modified: today,
    due: input.due,
    assignee: input.assignee,
    ownerName: null,
    gitPath: input.gitPath ?? null,
    description: input.description ?? "",
  });
  return { ttl: stateTtl.trimEnd() + "\n\n" + block + "\n", id: input.id };
}

/** Prefix header for a state.ttl the app writes itself (pod write backend). The
    `ekai:` alias is kept declared so docs round-trip with EmAI-origin pods; new
    blocks emit `mindp:`. Namespace IRIs are arbitrary — the parser keys off the
    prefix token, not the IRI — but must be DECLARED so CSS accepts the PUT. */
export const STATE_HEADER = [
  "@prefix : <#> .",
  "@prefix wf: <https://mind.dev/ns/workflow#> .",
  "@prefix mc: <https://mind.dev/ns/tracker#> .",
  "@prefix mindp: <https://mind.dev/ns/projects#> .",
  "@prefix ekai: <https://mind.dev/ns/projects#> .",
  "@prefix dc: <http://purl.org/dc/elements/1.1/> .",
  "@prefix dct: <http://purl.org/dc/terms/> .",
  "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
  "",
  '<#this> a mc:Tracker .',
  "",
].join("\n");

/** A valid, empty state.ttl (just the header) for a fresh project. */
export function emptyState(): string {
  return STATE_HEADER;
}

// ------------------------------------------------------------------- meetings

export type Meeting = {
  url: string;
  id: string;
  title: string;
  start: string;
  end: string | null;
  location: string | null;
  organizer: string | null;
  status: string;
  description: string;
};

export function parseMeeting(url: string, ttl: string): Meeting {
  return {
    url,
    id: ttl.match(/dct:identifier "((?:[^"\\]|\\.)*)"/)?.[1] ?? url,
    title: unesc(ttl.match(/schema:name "((?:[^"\\]|\\.)*)"/)?.[1] ?? ""),
    start: ttl.match(/schema:startDate "([^"]+)"/)?.[1] ?? "",
    end: ttl.match(/schema:endDate "([^"]+)"/)?.[1] ?? null,
    location: unesc(ttl.match(/schema:location "((?:[^"\\]|\\.)*)"/)?.[1] ?? "") || null,
    organizer: ttl.match(/schema:organizer "((?:[^"\\]|\\.)*)"/)?.[1] ?? null,
    status: ttl.match(/schema:eventStatus "([^"]+)"/)?.[1] ?? "scheduled",
    description: ttl.match(/schema:description """([\s\S]*?)"""/)?.[1]?.trim() ?? "",
  };
}

/** ldp:contains targets of a container listing (Turtle). */
export function parseContainer(baseUrl: string, ttl: string): string[] {
  const out: string[] = [];
  const re = /ldp:contains\s+((?:<[^>]+>(?:\s*,\s*)?)+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(ttl))) {
    for (const t of m[1].match(/<([^>]+)>/g) ?? []) {
      out.push(new URL(t.slice(1, -1), baseUrl).toString());
    }
  }
  return [...new Set(out)];
}

// ---------------------------------------------------------- member index (F4a)
// /<pod>/members/<user>/index.ttl — every project a user belongs to. The apex
// router reads this to decide where to send the user. Mirrors the writer in
// workspace/lib/turtle.mjs (renderMemberIndex) and its parser.

export type ProjectRef = { projectId: string; title: string; role: Role; host: string };

export function parseMemberIndex(ttl: string): ProjectRef[] {
  const entries: ProjectRef[] = [];
  for (const b of ttl.split(/\n\n+/)) {
    if (!/a ws:ProjectRef\b/.test(b)) continue;
    const projectId = b.match(/dct:identifier "((?:[^"\\]|\\.)*)"/)?.[1];
    const title = b.match(/dct:title "((?:[^"\\]|\\.)*)"/)?.[1] ?? projectId ?? "";
    const role = (b.match(/ws:role\s+ws:(\w+)/)?.[1] as Role) ?? "Member";
    const host = b.match(/ws:host "((?:[^"\\]|\\.)*)"/)?.[1] ?? "";
    if (projectId) entries.push({ projectId, title, role, host });
  }
  return entries;
}
